<?xml version="1.0"?>

<robot name="inspector_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="robot_namespace" default="/" />


  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find mm_description)/urdf/components/inspector_bot.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />



  <xacro:property name="ur5_z_location" value="${base_center_height + base_z_size/2}" />
  <xacro:property name="ur5_x_location" value="0.2" />


  <xacro:bare_base/>


  <xacro:ur5_robot prefix="" joint_limited="false"/>



  <joint name="ur_fixed_joint" type="fixed">
    <parent link="bare_base_link" />
    <child link = "base_link" />
    <origin xyz="${ur5_x_location} 0.0 ${ur5_z_location}" rpy="0.0 0.0 ${M_PI/2}  " />
  </joint>



</robot>
