<?xml version="1.0"?>

<robot name="inspector_bot" xmlns:xacro="http://ros.org/wiki/xacro">


  <xacro:arg name="robot_namespace" default="/" />

  <xacro:include filename="$(find mm_description)/urdf/components/wheel.urdf.xacro" />
  <xacro:include filename="$(find mm_description)/urdf/components/bare_base.urdf.xacro" />


  <xacro:property name="base_x_size" value="0.76" />
  <xacro:property name="base_y_size" value="0.46" />
  <xacro:property name="base_z_size" value="0.55" />


  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.44" />
  <xacro:property name="track" value="0.71" />
  <xacro:property name="wheel_vertical_offset" value="0.2" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.15" />
  <xacro:property name="wheel_radius" value="0.2" />
  <xacro:property name="base_center_height" value="${wheel_vertical_offset + wheel_radius}" />
  <!-- Base link is the center of the robot's bottom plate -->


  <!-- inspector_bot wheel macros -->
  <xacro:inspector_bot_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:inspector_bot_wheel>
  <xacro:inspector_bot_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:inspector_bot_wheel>
  <xacro:inspector_bot_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:inspector_bot_wheel>
  <xacro:inspector_bot_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:inspector_bot_wheel>


</robot>
